name: Amplify Deployment Comment

permissions:
  issues: write
  pull-requests: write

on:
  issue_comment:
    types: [created]

jobs:
  pr_commented:
    name: PR comment editing
    if: ${{ github.event.issue.pull_request &&  contains(github.event.comment.user.login, 'eLQeR') }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo Trying to edit comment on PR $NUMBER $USER_ID $COMMENT_ID
        env:
          USER_ID: ${{ github.event.comment.user.login }}
          COMMENT_ID: ${{ github.event.comment.id }}
          NUMBER: ${{ github.event.issue.number }}

      - name: Get current timestamp
        run: echo "current_time=$(TZ="Europe/Kyiv" date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV

      - name: Update comment
        env:
          AWS_AMLIFY_DOMAIN: ${{ vars.AWS_AMLIFY_DOMAIN }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          edit-mode: append
          comment-id: ${{github.event.comment.id}}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Access this pull request with subdomain here: https://pr-${{github.event.issue.number}}.${{ env.AWS_AMLIFY_DOMAIN }} <br/><br/> **Deployment was made at:** ${{ env.current_time }}
  
